### ISSUE TITLE
Font rendering in Mac OS X

### ISSUE THREAD

**Issue by ViNeek** [cgaueb/sgg#2]
Font rendering does not work on Mac OS X

**Comment by ViNeek** [comment]
Fixed!

**Comment by gsiros** [comment]
Confirmed to be working with the latest commit; tested on macOS Catalina 10.15.7

![Screen Shot 2020-12-20 at 22 08 32](https://user-images.githubusercontent.com/47118034/102723623-e2973f00-4311-11eb-965f-0eec084e4a78.png)
